version: 0.0
os: linux
files:
  - source: /
    destination: /dhaka/testgitpull2/
permissions:
  - object: /dhaka/testgitpull2/
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/pm2.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user
